repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
    args:
    - --maxkb=100
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args:
    - --fix=lf
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.4.1
  hooks:
  - id: prettier
    exclude: |
      (?x)(
        ^chart\/README\.md$
      )
    types_or:
    - css
    - markdown
- repo: https://github.com/adrienverge/yamllint
  rev: v1.26.3
  hooks:
  - id: yamllint
    args:
    - --config-file=.yamllintrc.yaml
- repo: https://github.com/norwoodj/helm-docs
  rev: 2a8b9ccc7fb024ba9c792b672b43eaa58f4c35d0
  hooks:
  - id: helm-docs-built
    args:
    - --chart-search-root=chart
    - --sort-values-order=file
