apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "lightdevops.fullname" . }}
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /cicd/
  targetRef:
    group: ""
    kind: Service
    name: {{ include "lightdevops.fullname" . }}-http
