kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "lightdevops.fullname" . }}
spec:
  parentRefs:
  - namespace: kube-system
    name: external-http
  hostnames:
  {{- range .Values.httproute.hosts }}
  - {{ toYaml . }}
  {{- end }}
  rules:
  - backendRefs:
    - name: {{ include "lightdevops.fullname" . }}-http
      port: 80
